### PR TITLE
create ClassInterface, which do an useless thing, in the bad place

### PR DESCRIPTION
**Pull request by kouinkouin**

### CODE REVIEW

**Comment by Cryde** [comment]
Our engineers team will have a look at that !
Thanks.

**Comment by kouinkouin** [comment]
Thanks for the quick reply.
I will wait by watching my laptop screen until you reply a second time.

**Comment by Cryde** [comment]
I think it's a good idea

**Comment by Cryde** [comment]
One of our engineers propose that you put this into the classes folder instead of vendor ...

**Comment by kouinkouin** [comment]
No, I will not do.
In ancestral epoch, vendors and sellers were respected. I want pay homage to them.
If you don't see the link, you have a closed mind, and stop to compute with computers.

**Comment by Cryde** [comment]
👎

**Pull request closed without merging**
